name: github Actions
on: push
env: 
    AWS_REGION: us-east-2

jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Testing 
              uses: actions/checkout@v4

            - name: Check Code Formatting 
              run: terraform fmt --recursive -check

    Provision:
        needs: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v4
            
            - name: setup Terraform
              uses: hashicorp/setup-terraform@v2
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
        
            - name: Terraform Init
              run: terraform init
        
            - name: Terraform Validate
              run: terraform validate
        
            - name: Terraform Plan
              run: terraform plan
        
            - name: Terraform Apply
              if: github.ref == 'refs/heads/main'
              run: terraform apply -auto-approve
             